* Config

This is my desktop configuration.

** Key Bindings

My custom key bindings are made using [[https://wiki.archlinux.org/title/X_keyboard_extension][xkb]] in the =layout/Layout.org=. It's a modified version of the wide [[https://colemakmods.github.io/ergonomic-mods/wide.html][Colemak mod]].

Here's a list of the most important changes:
- Caps Lock is mapped to Super
- The key next to the Z on ISO keyboards is mapped to Escape
- Most punctuation keys are mapped to Alt Gr + <letter key> to avoid having to reach far. For example, Alt Gr + P is mapped to %.

** Emacs Configuration

The Emacs configuration is following the [[https://github.com/daviwil/emacs-from-scratch/][Emacs from Scratch tutorials by David Wilson]], but also has personal changes. It can be found in =emacs/Emacs.org=.

** EXWM Configuration

It can be found in =exwm/Desktop.org=.

** Bash Configuration

The =raspberrypi.sh= script is intended to automatically set up my configuration on a newly installed Raspberry Pi OS.

** Plans

The future plans of this project are:
- To finish the Emacs from Scratch tutorials for the Emacs configuration.
