* =qucchia/dotfiles=

This is my desktop configuration, using Emacs and EXWM on a Raspberry Pi.

Most of the configuration is made under the =config= folder using Org mode files, which are then tangled with Org Babel to files in =home= and =root= and finally symlinked with GNU Stow so they can be accessed by the rest of the file system.

* Installation

*Requirements*: [[https://www.gnu.org/software/stow/][GNU Stow]].

To install the repo to the =.dotfiles= folder and set custom commands:

#+begin_src shell

  git clone https://codeberg.org/qucchia/dotfiles.git ~/.dotfiles
  export PATH="$HOME/.dotfiles/home/.bin:$PATH"

#+end_src

Then run =dotfiles-stow= to set up all the symlinks.

* Summary

Here’s a summary of the files in the =config= folder.
- In the =emacs= folder is all my Emacs configuration. See [[file:config/emacs/Emacs.org][Emacs.org]] for a description of all the files there.
- [[file:config/Theme.org][Theme]]: A theme to use across several programs.
- [[file:config/Browser.org][Browser]]: Configuration for the Vimb browser.
- [[file:config/FinalSetup.org][FinalSetup]]: Some self-reminders for setting up on a new machine.
