* qucchia/dotfiles

This is my desktop configuration, using Emacs and EXWM on a Raspberry Pi.

Most of the configuration is made under the =config= folder using Org mode files, which are then tangled with Org Babel to files in =home= and =root= and finally symlinked with GNU Stow so they can be accessed by the rest of the file system.

* Installation

*Requirements*: [[https://www.gnu.org/software/stow/][GNU Stow]].

To install the repo to the =.dotfiles= folder and set custom commands:

#+begin_src shell

  git clone https://codeberg.org/qucchia/dotfiles.git ~/.dotfiles
  export PATH="$HOME/.dotfiles/home/.bin:$PATH"

#+end_src

Then run =dotfiles-stow= to set up all the symlinks.

* Summary

Here’s a quick summary of the files in the =org-files= folder.

- =Emacs.org= is the main file for my Emacs configuration. It also loads the configuration from:
  - =Dolly.org=, which contains some functions to use the Tor proxy in Emacs.
  - =Dotty.org=, which is a package for automating actions in this =dotfiles= repository.
  - =Racket.org=, which plays a different Star Wars soundtrack depending on the day of the week.
  - =Email.org= is currently unused.
    
- =Desktop.org= is the configuration for EXWM.

- =Browser.org= is the configuration for Vimb.

Some other directories and files worth noting:
- =.bin/= contains custom bash commands which are loaded in =.profile=.
- =root/= is stowed to the filesystem root.
- =setup/= contains some self-notes for setup on a new machine and some pre-made Firefox configuration.
- =.xmodmap= maps Caps Lock to Left Super and the key between Left Shift and Z to Escape.
- =.xsession= starts EXWM.
