* qucchia/dotfiles

This is my desktop configuration.

* Installation

*Requirements*: [[https://www.gnu.org/software/stow/][GNU Stow]].

To install the repo to the =.dotfiles= folder and set up all the symlinks:

#+begin_src shell

  git clone https://codeberg.org/qucchia/dotfiles.git ~/.dotfiles
  cd ~/.dotfiles
  stow .

#+end_src

* Emacs configuration

The Emacs configuration is following the [[https://github.com/daviwil/emacs-from-scratch/][Emacs from Scratch tutorials by David Wilson]], but also has personal changes. It can be found in =Emacs.org=. Its contents is tangled to =.emacs.d/init.el=.

* Desktop configuration

My desktop configuration uses EXWM, which is set up in =Desktop.org=.

* Setup

- In =Setup.org= is the script intended to automatically set up my configuration on a newly installed Raspberry Pi OS. It's tangled to files in the =setup= folder.
- =FinalSetup.org= is a file which is opened in Emacs once the setup script is complete. It contains some configuration steps that can only be done manually.

* Other configuration

** =.bashrc=

Run when a Bash terminal is opened (unmodified).

** =.bin/=

Custom commands.

** =.config/=

- =.config/nvim=: Neovim configuration
- =.config/alacritty=: Alacritty configuration

** =.gitconfig=

Git configuration.

** =.profile=

Run when logging in.

** =.stow-local-ignore=

Files and folders which are not symlinked by Stow.

** =.xmodmap=

My custom key bindings are made using [[https://wiki.archlinux.org/title/xmodmap][xmodmap]]. It does the following:
  - Maps Caps Lock to Left Super.
  - Maps the key between Left Shift and Z (only on ISO keyboards) to Escape.

** =.xsession=

Startup script that runs EXWM.
