#+title:Raspberry Pi Final Setup

To get right into the grind...
- Run =bash ~/.xsession= to open Emacs with EXWM
- Run =emacs= to open Emacs without EXWM
- Run =nvim= to open Neovim

Additional setup:

* Set up SSH
#+begin_src shell

  ssh-keygen -t ed25519 -C "qucchia0@gmail.com"
  cat ~/.ssh/id_ed25519.pub

#+end_src

Add the output key to codeberg.org.

* Clone repositories

#+begin_src shell

  dotfiles-clone

#+end_src

* Install icons

You'll have to restart Emacs for the changes to take effect.

#+begin_src emacs-lisp

  (all-the-icons-install-fonts)

#+end_src

* Set up audio output

By default, the audio output is set to HDMI. To change it to the headphone jacks, follow these steps:
1. Run =lxsession= on eshell.
2. Find the volume icon > Default Sink > Built-in Audio Analog Stereo.
3. Kill =lxsession=.

* Import GPG key

Import the GPG key from a USB stick by running:

#+begin_src shell

  gpg --import-options restore --import <FILE>.gpg

#+end_src

* Configure Firefox settings

- General: Make default browser

- Network: Manual proxy congiruation: SOCKS Host: 192.168.1.38 Port 9050

- Search: DuckDuckGo

- Privacy: Delete cookies and site data when Firefox is closed. Exceptions:
https://codeberg.org
https://freecodecamp.org
https://github.com
https://google.com
https://moodle.ins-mediterrania.cat
https://web.whatsapp.com

- Disable logins and passwords

- HTTPS-Only Mode: enabled

** Extensions

Privacy:
- Ublock
- NoScript
- HTTPS Everywhere
- Google Container
- Don't track me Google

Enhancements:
- Dark Reader
- Enhancer for YouTube
- Return YouTube dislike
- SponsorBlock
