#+title:Setup

* Installation

** Linux

*Requirements*: [[https://www.gnu.org/software/stow/][GNU Stow]].

#+begin_src shell

  # Install the repository
  git clone https://codeberg.org/qucchia/dotfiles.git ~/.dotfiles

  # Set custom commands
  export PATH="$HOME/.dotfiles/home/.bin:$PATH"

  # Set up the symlinks
  dotfiles-stow

#+end_src

* Tangling Emacs files

To tangle all of Emacs’ files, open it for the first time and run (e.g. with =M-:= or in the Scratch buffer):

#+begin_src emacs-lisp

  (let ((dotty-directory "~/.dotfiles"))
    (require 'org)
    (org-babel-tangle-file (expand-file-name "config/emacs/Dotty.org" dotty-directory))
    (load-file (expand-file-name "home/.emacs.d/lisp/dotty.el" dotty-directory))
    (dotty-tangle-org-files))

#+end_src

Replace =~/.dotfiles= for the directory where this repository is located.

* Running

- Run =dotfiles-start-exwm= to open Emacs with EXWM.
- Run =dotfiles-start-emacs= to open Emacs without EXWM.

If you get a ‘failed to check signature error’:

#+begin_src emacs-lisp

  (let ((package-check-signature nil))
    (package-install 'gnu-elpa-keyring-update)
    (gnu-elpa-keyring-update))

#+end_src

* Additional setup

** Set up SSH
#+begin_src shell

  ssh-keygen -t ed25519 -C "qucchia0@gmail.com"
  cat ~/.ssh/id_ed25519.pub

#+end_src

Add the output key to codeberg.org.

** Clone repositories

#+begin_src shell

  dotfiles-clone

#+end_src

** Install icons

You'll have to restart Emacs for the changes to take effect.

#+begin_src emacs-lisp

  (all-the-icons-install-fonts)

#+end_src

** Set up audio output

By default, the audio output is set to HDMI. To change it to the headphone jacks, follow these steps:
1. Run =lxsession= on eshell.
2. Find the volume icon > Default Sink > Built-in Audio Analog Stereo.
3. Kill =lxsession=.

** Import GPG key

Import the GPG key from a USB stick by running:

#+begin_src shell

  gpg --import-options restore --import <FILE>.gpg

#+end_src

** Configure Firefox settings

- General: Make default browser

- Network: Manual proxy congiruation: SOCKS Host: 192.168.1.38 Port 9050

- Search: DuckDuckGo

- Privacy: Delete cookies and site data when Firefox is closed. Exceptions:
https://codeberg.org
https://freecodecamp.org
https://github.com
https://google.com
https://moodle.ins-mediterrania.cat
https://web.whatsapp.com

- Disable logins and passwords

- HTTPS-Only Mode: enabled

*** Extensions

Privacy:
- Ublock
- NoScript
- HTTPS Everywhere
- Google Container
- Don't track me Google

Enhancements:
- Dark Reader
- Enhancer for YouTube
- Return YouTube dislike
- SponsorBlock
